version: "5.0.1"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - nl2sparql
      - graphdb

  nl2sparql:
    build: ./nl2sparql

  ui:
    build: ./ui
    ports:
      - "5000:80"
  
  graphdb:
    image: ontotext/graphdb:10.6.1
    container_name: graphdb
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home

volumes:
  graphdb-data: