version: "5.0.1"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"

  ui:
    build: ./ui
    ports:
      - "5000:5000"
    depends_on:
      - api-gateway
  
  nl2sparql:
    build: ./nl2sparql
