version: "5.0.1"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - nl2sparql

  nl2sparql:
    build: ./nl2sparql

  ui:
    build: ./ui
    ports:
      - "5000:80"